<?php

namespace Sweepo\BettingBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * BetRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BetRepository extends EntityRepository
{
    public function findForTable($user, $filter)
    {
        $qb = $this->createQueryBuilder('b');

        $qb->where('b.user = :user')
            ->setParameter('user', $user)
            ->orderBy('b.date', 'DESC');

        return $qb->getQuery()->getResult();
    }
}
