fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"

sweepo_betting:
    resource: "@SweepoBettingBundle/Controller/"
    type:     annotation
    prefix:   /

sweepo_user:
    resource: "@SweepoUserBundle/Controller/"
    type:     annotation
    prefix:   /

sweepo_core:
    resource: "@SweepoCoreBundle/Controller/"
    type:     annotation
    prefix:   /

login:
    pattern: /login
    defaults: { _controller: SweepoUserBundle:Backend:login }

login_check:
    pattern: /login_check

logout:
    pattern: /logout

# Internal routing configuration to handle ESI
#_internal:
#    resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#    prefix:   /_internal
