parameters:
    database_driver:   pdo_mysql
    database_host:     localhost
    database_port:     3306
    database_name:     sweepo_dev
    database_dev:      sweepo_dev
    database_test:     sweepo_test
    database_user:     root
    database_password: root

    mailer_transport:  smtp
    mailer_host:       localhost
    mailer_user:       ~
    mailer_password:   ~

    locale:            en
    secret:            GFE45Y456RHYRTYUHEhdfghryUT67RsdfhryU67TR6YETTGDTUrurTDHR56TDHFGBV
